export default {
    testVideo: {
        title: 'testVideo',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: true,
        titleVideo: 'cake',
    },
    testImg: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test1: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test2: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test3: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },    
    test4: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test5: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test6: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test7: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
    test8: {
        title: 'testImg',
        titleImg: 'ball',
        content: 'Test1',
        isVideo: false,
        titleVideo: 'none',
    },
}